### ISSUE TITLE
Test failure and usage errors

### ISSUE THREAD

**Issue by kav** [Schniz/reql-pointfree#2]
Once configured correctly _shiftlift_ > _users_  > `{firstName:'Gal', lastName:'Schlezinger'}` running the rethinkdbdash tests leads to a failure in  'should work with twice composing'.

Seeing the same in usage. The calls all go through correctly but then the library crashes with an unhandled:

``` shell
 Uncaught TypeError: target.apply is not a function
      at tryCatcher (node_modules/rethinkdbdash/node_modules/bluebird/js/release/util.js:16:23)
      at Promise.successAdapter [as _fulfillmentHandler0] (node_modules/rethinkdbdash/node_modules/bluebird/js/release/nodeify.js:23:30)
      at Promise._settlePromise (node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:558:21)
      at Promise._settlePromise0 (node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:606:10)
      at Promise._settlePromises (node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:685:18)
      at Async._drainQueue (node_modules/rethinkdbdash/node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/rethinkdbdash/node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/rethinkdbdash/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by Schniz** [comment]
I ran the tests and I got

![image](https://cloud.githubusercontent.com/assets/2054772/19627027/f827a2f2-9946-11e6-8c1f-02e6d5ded75d.png)

But then I when I ran them again:

![image](https://cloud.githubusercontent.com/assets/2054772/19627032/0b7a7b2c-9947-11e6-8686-350095785eca.png)

It looks like it is not deterministically fails the tests. I really don't understand why.

If we run the test by itself it is always pass:

![image](https://cloud.githubusercontent.com/assets/2054772/19627111/319bd548-9948-11e6-8227-913a6b262031.png)

**Comment by Schniz** [comment]
So strange 🤔
